/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Error
import io.swagger.client.model.Successfulresponse
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Lists all the opportunities under a specific funder
   * 
   * Expected answers:
   *   code 200 : Successfulresponse (A response on successful API call)
   *   code 400 : Error (An error when an illegal input occurs)
   * 
   * @param &#x60;industry type&#x60; 
   * @param pageLimit 
   */
  def fundingOpportunitiesGet(&#x60;industry type&#x60;: Option[String] = None, pageLimit: Option[Int] = None): ApiRequest[Successfulresponse] =
    ApiRequest[Successfulresponse](ApiMethods.GET, "https://localhost", "/fundingOpportunities", "application/json")
      .withQueryParam("industry type", &#x60;industry type&#x60;)
      .withQueryParam("pageLimit", pageLimit)
      .withSuccessResponse[Successfulresponse](200)
      .withErrorResponse[Error](400)
      

}

